### ISSUE TITLE
I'd like to Donate an amazing racing script

### ISSUE THREAD

**Issue by CaptainSwellHell** [ChainedDev/CityLife#110]
It's a racing script much like the one seen on the NoPixel servers before they updated to using the phone. It's very easy to use and I know people have a lot of fun racing. I think it would add a little bit more to do. At the very least... distract people for a little while instead of killing each other or robbing banks.

**Comment by gullidog** [comment]
Thanks for the offer! Do you mean the one which displays 'Press [E] to join' above the car? We used to have a race script. However, it was removed due to the lack of use from people of it, we also discovered a major exploit with it! Which is why it was overall removed. Although, if more people would like a racing system implemented back in then that is something we could work on!

**_gullidog_**

**Comment by ChainedDev** [comment]
Vrrrm Vrrrm
