### ISSUE TITLE
SERIOUS REQUEST - SQUEAKER AND DANNY HUNTING

### ISSUE THREAD

**Issue by TerryDavis-CL** [ChainedDev/CityLife#183]
**Is your feature request related to a problem? Please describe.**
Yes. The problem is squeakers and default dannys. At any given time the server is at minimum HALF squeakers and people in the server for the first time. The quality of RP is non existent and our server looks like a vmenu server on a daily basis. This sucks. This place used to be awesome.

**Describe the feature you'd like**
I would like the legal ability to hunt squeakers and default dannys. A hunting license with access to the ban hammer if you will. This will give me the ability to clean up our community and get back to a server I can stream in.

**Describe alternatives you've considered**
Whitelisting, mass bans, GOING BACK TO THE OLD RULES WHERE THIS SHIT WAS NOT TOLERATED

**Additional context**
Please.... it's gotten REALLY bad

**Comment by Aspratic** [comment]
Ummmmm

**Comment by Aspratic** [comment]
I think maybe opening a staff ticket would be a better way of handling this. The server is experiencing massive growth and new players are bound to come. However we are always working to keep the server fun and a quality place to RP. If you would like to talk to staff about this, a ticket is the place to do it. Not in a github post.

**Comment by TerryDavis-CL** [comment]
It’s been discussed and ignored multiple times. I’m not the only person who feels this way. You guys know what’s going on. Don’t give me the “growing server” nonsense. At any given time over 50% of our server is in it for the first time. That’s not growth it’s filling a server with no OG players

**Comment by Aspratic** [comment]
I mean there are a lot of 'OG' players tbh and not many players are default dannys. Though I understand the issue and what your saying, even if it was presented as a joke

**Comment by TerryDavis-CL** [comment]
Having this discussion with you is pointless as you choose to ignore facts and fall back on nonsense. There are NOT a lot of OG players TBG. And my suggestion wasnt a joke. It was a suggestion on how to unfuck the server. The in game server is a shit show. Its not that way because of the community. Its first time players abusing OOC and staff turning a blind eye. Its a 12 yr old VDMing 5 people at legion and being unbanned because he blames his little brother. Ive had friends here perma banned for so much less. Unfuck the server or it will never be what it used to be

**Comment by Aspratic** [comment]
People come and go. I am living proof of that, I personally don't want to go back to the time where you could buy 100 Bricks of coke from a tweet at the Vanilla Unicorn that says selling white tacos, or have rdm fests blackhand vs crips or snow patrol. I dont wanna go back to where 25 people stood on legionsquare with their supercars that drove like spaceships sitting on the steps of legion, I don't wanna go to the time where everyone could run around with AR's on their back. This post is so negative and there are so many BETTER ways to handle this issue. Im not saying its not an issue, because it most certainly is, but complaining about it isnt the way to go about things. 
Heres a little pinned comment from MONTHS ago before I was even staff. I think you should read it.
![image](https://user-images.githubusercontent.com/52019072/81336902-22a5fc00-9078-11ea-8d8c-2c00314b4f2c.png)

**Comment by Aspratic** [comment]
Making this github doesn't help or solve anything. YOU are part of the problem if you actually think killing every danny and squeaker then banning them is the problem. 
Coming from someone who has been apart of this community for a while and has seen it grow and become what it is today. Some of your "OG's" are not good rp'er and have in-fact created more issues then any new player. If your some OG and love the community, making this post isn't the way to help. At all.

**Comment by Droshky** [comment]
bro ur like hitler

**Comment by l-Crynic-l** [comment]
It should just be in rules: If you don't change your outfit / face & hair, then you may be subject to mistreatment and disrespect. 
simple as that. No need for killing, but just a warning.

**Comment by JJG1997** [comment]
It is a rule :D - /report we can sort them out

**Comment by TerryDavis-CL** [comment]
Right... we should just spend our time reporting every person we see doing this. Definitely helps immersion and is great content for streams. You may not have been part of the good RP pre wipe but a lot of us were. In game OOC being used as a play through guide was never a problem pre wipe. The spawn point wasn’t aids pre wipe either. The city before was full of people who played consistently. Today at least half are first time players and people looking to play GTA in a modded server. We all know and acknowledge this is a problem, yet I’m the only one proposing a solution. Instead of complaining about how bad shit used to be why don’t you use your time trying to unfuck the server... you know seeing that now you ARE staff... and this seems like something you should be handling....

**Comment by gullidog** [comment]
Due to the server increasing in popularity, which we are immensely grateful for, there will be unfortunately be people who are new to RP. This has been recognised by management, so we are always constantly finding new ways to help them in their path without hindering their own RP and others. One example would be the guide, which we implemented to be a detailed easy to access FAQ for the new community. We are also in the process of developing new ways to assist new players. However, you do have to remember that we were all new to RP once and asked silly questions therefore you do have to be lenient to a certain extent. I understand that some people join to be shitlords which is why we appreciate our community reporting this to use through /reports and discord tickets so we can keep this to a minimum. Which is one downside to us growing, however new players to the server are not necessarily a bad thing - I have seen amazing RP from people who are new to the new server. So I feel that it is not fair to put them all under the category of shitlords. If you would like to continue this could you please make a server question ticket in discord. And remember to use /reports and discord tickets to report any issues with other players! :)
**_gullidog_**

**Comment by klucx** [comment]
Correction: There will be an unfortunate amount of people who are new to RP

**Comment by klucx** [comment]
I agree with both sides of the argument here. And I have no issue at all with new RPers, and have the time it isn't the problem. But there's danny's and supreme hoodie folks who just come into the server, totally aware of what you can/can't do, but choose to abuse it and shitlord and break rules on just another FiveM server. If I'm not getting earraped by a new person that has voice activity on, I am more than happy to guide them in their new city. Just for some reason compared to pre wipe, there is an excessive amount of people who are just straight dumbasses. I agree with half of what Colby said, but I 100% agree with the pinned comment he posted. I make reports way too often. I see people being shitlording idiots way too often. The problem is with people new to FiveM in general is they don't know any better than playing it like it's GTA V. With this being said, I think more noobs should at least get a warning before being yeeted out of the server. I am more than happy to show people their way, which is one of the reasons I've been wanting to become staff for months. I want to help people and improve the quality of RP. I want to help people create RP.

**Comment by ChainedDev** [comment]
Report them if you see them and staff will handle it
