### ISSUE TITLE
Houses that don’t need D8s

### ISSUE THREAD

**Issue by SigilOG** [ChainedDev/CityLife#254]
**Is your feature request related to a problem? Please describe.**
Yes because D8 agents don’t respond, but are clocked in collecting paychecks...

**Describe the feature you'd like**
It should be made so that there are houses you can walk up and just buy anywhere at pre-determined set prices. Or the D8s or staff should be able to set them up as listings that can be purchased anytime. This can run on a similar system like how PDM is ran and D8s can also offer discounts on these listings if they choose to. 

**Describe alternatives you've considered**
Obviously the alternative is to replace all the current D8 people who aren’t doing their jobs with people who will. They aren’t messaging people back that have waited hours doing so and they always have a long list of people saying they are looking for a D8 and when they are online clocked in, ignore everyone. Can they do their damn job?

**Additional context**
This suggestion is a solution to help frustrated players get ahold of D8s or to purchase homes with less issue. I understand that every home is to be uniquely owned, but unfortunately that system is broken if the D8 agents can’t even be bothered to appraise a house! People waiting on a D8 got robbed because they were sitting around waiting for a D8... those individuals are extremely unhappy. But, at the same time it wouldn’t have happened if the D8 that’s been online was doing their job. Since I’ve been in the server I’ve never seen a single D8 that actively did their job when people were looking for homes and it needs to be addressed by adding alternatives to purchasing homes.

**Comment by Aaronzenn** [comment]
Okay so let me clear a few things up. 

Firstly, just because D8 are clocked in and aren’t with you at that very moment, doesn’t mean they’re just paycheque farming. People email us asking about properties, pictures, prices, videos of the neighbourhood or appointments. Staff don’t need to get involved in RP situations. If you feel like you can do the job, apply.

Secondly, the difference between PDM and Dynasty, is that there are a set number of vehicles to purchase with a predetermined price. Houses are far more different, price factors differ for a multitude of reasons. Neighbourhood, What the house has to offer e.g Garage, swimming pool, etc.. Having a system, where people could just flex the E Button to just buy a house reduces the RP in the city, what would be the point. Also, it would take weeks on weeks to set prices on houses all over the city. Sorry, but your idea isn’t practical at all.


Lastly, we’re not crime stoppers. You can’t blame dynasty for getting robbed. If you’ve been a victim of a crime? Report it to police. Also, if you were robbed, there has to be good RP behind it. If people are robbing you for material gain and wiping your inventory, then make a ticket detailing what happened. Don’t correlate you getting robbed to the fact “D8 aren’t available”

P.S Like I stated earlier, if you feel like you can do the job, apply. To be transparent as possible, a lot of applicants either miss the point of being a D8 agent when answering the questions, or do poorly in the interview, going OOC or just copying answers from the internet. It’s not a difficult process, and we’re not expecting a really good response, just some enthusiasm  about the job

**Comment by SigilOG** [comment]
When people reach out they are being ignored... so your statement to reach out is invalid in my observations to date. The process can be changed significantly for the better. 

Simply changing the #looking-for-agent channel to require a D8 to respond to everyone and schedule appointments instead of being left hanging should be a priority and something should be done to make it easier to get ahold of a D8 or at least get a response. I have photo proof of an individual whom messaged a D8 and never received a response until it was in the public discord. That’s not acceptable. You guys need to be responding. Even if it is a simple, “hey I got your messages, send me some times and dates that we can further this conversation.” Simple. Done. Move forward. That is practical.

Secondly, you state setting prices for houses all over the city isn’t practical because it would take weeks and weeks. Okay so? I didn’t build any of my businesses in a day either. I didn’t create a whole indie video game in a day. It takes time and I understand that, but saying something isn’t practical because it takes time is an excuse to be lazy. That is unacceptable. Whereas, I see your point to the role play value(s) being diminished and I get that. But if the D8s aren’t doing what needs to be done as it is and people are constantly left hanging and angered than there is no RP value as it is anyways. No one wants to role play the angry customer. Like c’mon. Now my suggestion did not say to price all the houses. I suggest pre-pricing some that they can flex an e button to purchase and takes off the market or the D8s create a way to list foreclosures for buying. It would remove a lot of stressors on everyone and would create a role play in the foreclosing of properties, listing, and the like. 

Now moving on, I would apply for a position to be a D8 but that isn’t the role my character is designed around. I could do the job in my sleep just like I run three businesses pretty much in my sleep. I have no problem directing over 100+ people on what to do and how to do it on a daily basis. My point here is to eliminate your excuses and the other D8’s excuses on why a good amount of people in the city believe the D8s we currently have are worthless and your response furthers why y’all should be replaced and why new measures, procedures, processes, and mechanics should be implemented. The system currently is faulty on multiple different levels and should be investigated for integrity and also for availability and playability for the community. 

Lastly, the whole point of stating the robbery was not to blame D8s but to make a point. We are sitting around WAITING for you guys where allegedly we are told to go. We have accessed the different channels, yellow pages, Twitter, discord and even trying to find a D8 by talking to people in city. And guess what. Nothing. Not a soul. It takes making a stink in suggestions and in one of the public channels to get anything remotely close to being done acceptably. That is not what needs to happen to get help after days of trying. That is ridiculous and the people running the show need to take a serious look in to this particular issue. We sit around waiting and people will come and see that. That hurts roleplay value if we sit around like sitting ducks waiting for someone to figure out what to do in life... no. That makes us an easy target when a D8 says they are finally going to come and next thing you know they don’t and we are getting robbed. You got people pissed off because they spent $120 to get rewards that they lost because of that. That’s unacceptable. If it truly is an appointment system, don’t tell people to go to the Arcadius. It makes ZERO sense. That’s just asking for FailRP at this point. Especially if y’all never show up. I understand you guys have lives and other things you want to do. But if I’m online and it shows there is a D8 online, clocked in, and they aren’t responding to anyone or actively doing D8 work than that is in fact paycheck farming and the D8s doing so should be investigated for their integrity and what they are doing while clocked in.

**Comment by jackofalloffs** [comment]
Agents that are in the city clocked on are always with clients. If they arent, report them. Agents arent obligated to stare at twitter 24/7 in the city when they are with clients. we tell you to go to the arcadius center because thats our office.
If you cant get ahold of an agent in game, then DM one. It has been said multiple times in the discord that that is an option but yet i havent received a dm from you ever. 

Being robbed again has nothing to do with dynasty. Dynasty doesnt require cash at hand. if dynasty asks you to go to the office then go empty handed. you literally dont need anything on your person in order to get a house appraised or to buy a house. if you think an agwnt telling you to meet him at the office is FailRP then im not sure what to even tell you. You have much to learn.

Buying houses isnt supposed to be an easy, simple task. Take the time and effort to reach out to an agent and one will reach back to you.

**Comment by Decirus** [comment]
From what I read you just seem upset that you didn't get served. Whenever we are clocked on we always are doing D8 work, that being with a client or making listings, etc. If you really need to speak to a D8 agent actually dming us would be helpful, stating "hey when you available" you will 9/10 get a response. Typing "d8 needed" in the #looking-for-agents tab is simply not enough. If you check the pins in that tab you will be able to see that I've stated "If you're looking for an agent at certain times its best to email us so we can both set-up an appropriate time, makes things easier on the both of us." We have lives too, I'm not just gonna jump on at 3.40 am just to sell you a house just cos you want it. I'm on duty every single day, and if you can't catch me on duty thats not my fault.  As I said, its best to just dm us so we can set up a time appropriate for the both of us.  When we say "meet me at the Arcadius Centre" it means for you to go there and wait for us, if we aren't there, its means you were too late and we are already with another client at that point. We aren't accountable for you being robbed at our office, and it certainly isn't "setting you up" for FailRP by us asking you to meet us there. By you making this suggestion of buying houses without D8 just ruins the whole concept of D8 and reduces good roleplay. There is also just a few of us, so I'm sorry we can't just get to everyone instantly. It seems you are making this suggestion because of a bad experience, but we aren't the ones to blame. Also got to take in the fact that we also want to roleplay, not constantly being on duty 24/7. Thats why my preferred method of arranging meetings is by dming me personally on discord. Once again, like my colleague said, if you think you're fit for the job then apply yourself using #applications.

**Comment by McFry36** [comment]
What if D8 created a google form for people to fill out when inquiring about a property? I’d have to agree the current system is a bit flawed on getting a hold of a D8 agent but I haven’t seen a single resolution suggested just a bunch of people complaining or defending. Which I think everyone deserves as the current system is deff not as effective as it could be.

**Comment by SigilOG** [comment]
This is a resolution;

- Create some kind of way that submits a form to schedule an appointment with a D8. Lock the #looking for agent channel and change it to #schedule an appointment. Make it so everyone receives a response within 24-48 hours.

- Make a schedule that every D8 has a set day and timeframe they can make so that everyone knows for walk ins. This doesn’t have to be an 8 hour shift, just like an hour here and an hour there... 

- Utilize the dynasty listings channel to show off properties that have been already appraised and can be purchased without a D8. This can be a very limited amount of homes so that when D8s aren’t available someone else can step in Or plays can do it themselves...

- Crate an application in game that allows people to submit role play requests for a D8 that D8s will get notified of. And had a calendar where everyone can see open appointments to be scheduled if D8 put it.

- I suggest making the paycheck less and giving a commission of the sales of homes to influence and incentivize D8s to want to sell more houses. 

- Creating a catalog overall on a large amount of homes all over the city. This would make it so D8s aren’t needed for “price checks” all of the time. This would be similar to how it is IRL and that when players find homes they like they can reach out to a D8 to place a bid or to negotiate a different price. 

- Make it so that if someone is having a difficult time getting ahold of a D8 that there is a way for the D8 to do a “virtual” meeting or a “phone call” role playing it out to discuss homes. Having a catalog setup will make this easier and give the D8 less stress to deal with pricing for overtime and allow for them to do more real estate of showing off homes.

- D8s host open house events. Just like IrL D8s should do a few open house events to show off like 2-3 homes for people to come see houses and have D8s show them off. I think this would be a really cool way to implement more role play value even if making a catalog.

- It can also be further role played out for renovations. This would be a lot of work imo from a programmer and a graphic designer to implement housing customization. Even on a limited scale, but I think this would be a really cool idea that prior to purchasing a home that the D8 sells renovations and add ons to homes creating more role play value.

Overall all of these suggestions would create a better system, and a better way to roleplay out the buying of a home.



-

**Comment by jackofalloffs** [comment]
I like and agree with most of these ideas and some are already in the works. but like previously stated all of this takes time. its not just like all of this stuff can be implemented tomorrow.

 D8 agents already get commission for houses sold. The paychecks are negligible compared to the commission from houses.  

We are working on a catalog, I dont think you realize how many homes there are in Los Santos. We are going to publish a full catalog very soon as agents go around the city on duty and take pictures and appraise homes for said catalog. 

I still encourage more people to email agents if you cant contact one in the city so we can set up times and appointments. Every person that has contacted me personally for an appointment has gotten one. I can work more to better my agents to reply to more appointment requests as well as get more agents in the city. 

All of this is a process that we are working on. Dynasty is still a relatively new business and job and we are still working to perfect it. Thank you for your suggestions we will take them into account moving forward.

**Comment by skiredd** [comment]
> * Create some kind of way that submits a form to schedule an appointment with a D8. Lock the #looking for agent channel and change it to #schedule an appointment. Make it so everyone receives a response within 24-48 hours.


there already is a way

its called DMING THEM ON DISCORD

**Comment by McFry36** [comment]
Gonna be honest I mean more power to them but the last thing I’d want is people DMing at all hours of the day to buy a house in CityLife. Form System seems more applicable. But hey you want your DMs to blow up go for it.

**Comment by SigilOG** [comment]
The forms give all D8s equal ability to respond. There is no list of whose a D8 so how are people supposed to know who to dm? I guess we should all just @D8 agent in discord to figure it out ? 

No a form system is better for all and if implemented will see better results. You can use google forms or type form it doesn’t matter.

**Comment by JJG1997** [comment]
Pinned messages in Looking for agent

**Comment by gullidog** [comment]
At the end of the day, the people complaining about having to go through a Dynasty 8 agent and interact with another person are the people who don't want to RP or cannot be arsed. So maybe just RP??
