### ISSUE TITLE
SASP Vehicles - New or Rework

### ISSUE THREAD

**Issue by JJG1997** [ChainedDev/CityLife#286]
**What is the reason for this balance request?**

Right now, our fastest vehicle is the mustang which tops out at around 185 (full upgrades) on the highway. There are much faster cars than this that criminals use which leave the mustang in the dust.

**What solution would you like?**
Either a faster vehicle to match the super cars in the city or a rework on the mustang. 

**Additional context**
Couple of cars that can be added if necessary.

https://www.gta5-mods.com/vehicles/mercedes-benz-amg-gt-r-2017-hot-pursuit-police-add-on-replace-template-yca-scrat

https://www.gta5-mods.com/vehicles/porsche-panamera-turbo-need-for-speed-hot-pursuit-police-car

https://www.gta5-mods.com/vehicles/porsche-718-cayman-s-hot-pursuit-police-add-on-replace

**Comment by thejorhanstahl** [comment]
Additionally, I'd suggest a buff to out BMW bike (or adding some new one that is better)

Currently, the BMW Bike requires Training, it's obtainable since Trooper 1 and specific requirements are needed to take one out.
Bike, unfortunately, is very underpowered for it's "prestigious" use, bear in mind that going as moto unit means-
- The risk connected with going down if you barely touch anything;
- Not being able to transport criminals;
- You have 0 cover from any shots fired at you and you can be brake-checked;
- Uncommon use of it.

With those risks in mind, there should be advantages to going out as moto, but currently, there is little to no advantages.
Main problems of the bike:
- Low speed (caps at 120mph- might be even lower than Crown Vic);
- Awful turning at high speeds ( it's literally worse than any civilian use bikes- they simply outperform this one);
- No upgrades for the bike- no armor, turbo, engine upgrades;
- Inconsistent;
- Most likely caused by the lack of armour upgrade- anything that barely scratches your bike will make it smoke.

Seeing these multiple problems there is no sense to even use the bike unit due to it being worse than all PD vehicles and Far worse than Civ vehicles. With that bike needs either a buff, upgrades, better turning etc. or a new one should be added with better performance.

**Comment by TheLitteralIcemanStraightOuttaFinlandia** [comment]
Is mister trying to get the Dubai police's Bugatti chion in the city or something. Pepega
https://sv.gta5-mods.com/vehicles/bugatti-chiron-hot-pursuit-police-add-on-replace-template

**Comment by ChainedDev** [comment]
nah the ones we have are fire especially the white livery
