### ISSUE TITLE
Ways to earn citizenship in to the city

### ISSUE THREAD

**Issue by TimmyTwoStep** [ChainedDev/CityLife#369]
**Is your feature request related to a problem? Please describe.**
Depends on how you would look at it, I personally don't see it being problem related. Everyone would look at it differently. 

**Describe the feature you'd like**
The feature I would like to see is two forms of whitelisting. Some people are afraid it would kill the city off, but myself and others would disagree and say that the city of CLRP has gotten a pretty decently sized community of players who look for a solid Role play experience. 

The two forms of whitelisting I've came up with are either through an application or by donations towards the server, I think this would be a good middle ground for the server because people who wouldn't want to do an application to get in to the city could just pay their way in. Yes it might seem a little scummy, but I would be one that is all for it and I also think the city would deliver on the RP experience so it would be well worth the investment.

Also for the people who wouldn't want to pay to get in they could just simply go through an application process and chances are if they pass, they would be pretty well invested in to the role-play scene so they would most likely bring a very good experience to the city and its citizens,

**Describe alternatives you've considered**
I haven't came up with any alternatives because this suggestion is either you're in or you're out. If it goes through there should be some form of grand father citizenship for players that have stuck around inside the city for a while. 

**Additional context**

I think the city of CLRP has a very good community and they would all like to see a form of whitelisting inside the city. It makes a better community and experience for the players, I am not against Danny's unless they are people being absolute trolls, doing this would filter them out and new comers can still get a chance to get inside the city which I know is something the city wants to be known as a place where new players who want to get in to RP can come to CLRP. This can also reduce the chances of hackers tremendously unless they really want to pay for a way to get inside of the city and ruin it for everyone. At least the server is getting a donation for it right?  

I believe majority of the city would like to see some form of earned citizenship regardless if the player base would drop, but if you think about it, when it all works out the player base would catch back up to its normal numbers. It's just something that would make the city offer a more consistent serious role-play experience.

**Comment by Forkedup** [comment]
In my honest opinion, our city is structured around it being open to the public. 

While it certainly can change, and while I also certainly understand your side of the request. I believe there are other possibilities we could do as well.

I'm currently looking at things like more Discord & Steam related verification. Right now anyone can fly into the city and access it, even without being in Discord / without a code. Meaning if they have a good cheat menu that's undetected, they can still open a menu and cause chaos. I was thinking more having all users have to verify / link their steam in order to get access granted into the city.  (Would be done automatically by a Discord bot, bot would give a rank when verified). Along with this, I would also implement a script that wouldn't even allow you to join the server unless you had the Verified role on discord (probably civilian). This would probably prevent a lot of shit, and will most likely be the route we take.

Like I said, a whitelist is not impossible, more so last straw type thing

**Comment by TimmyTwoStep** [comment]
I do like idea that you shared, it seems as if you're going for a whitelisting without the application process hence the steam IDs.

I'm not sure if you can set up a bot to do it, but I think for discord verification should be people typing a command inside a channel for authentication. Keeping the same thing that the city currently has with the rules for the password but in this case the command for discord. Setting it up only discord access is given once the command is typed in to channel they can't see the history of seems like a strong solution.

The steam IDs are basically white listing just without the application and this sounds like a decent middle ground for people, not sure if this can be done automatically or it would have to be done manually, but this would definitely increases the city's experience, allowing people who go the extra step to join and also reduce the chances of hackers.

After typing this I basically realized I typed the same exact you said.

**Comment by Forkedup** [comment]
Lmao, no worries.

As I stated, the bot would message you upon joining the discord asking for you to link your steam. After doing so it would remain connected, and if you're not verified you will not even be able to join the server. Along with this, if you do join the server and are new, you'd need the password as well.
