### ISSUE TITLE
Moving the STU

### ISSUE THREAD

**Issue by km4411933** [ChainedDev/CityLife#378]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the feature you'd like**
I've noticed that in other cities, the Studio is right across from the VU. I think it would get a lot more use if that was the case instead of being so far up north. Just a small quality of life change that would promote more interaction in the city.

**Describe alternatives you've considered**
Just thinking of a location switch for the Studio so it gets used more.

**Comment by ChainedDev** [comment]
We looked at many options before adding one but the main concern was adding in extra lag, because everything gets added, ends up adding more stress to performance in one way or another. We picked it out of the city and even looked at the one next to VU but felt it would just hinder the already sometimes poor frame rate mid-city

**Comment by km4411933** [comment]
ah, that makes sense. Performance gets crazy when going into that part of town, at least for me.
