### ISSUE TITLE
EMS taking away Armor

### ISSUE THREAD

**Issue by Baja-Blast** [ChainedDev/CityLife#403]
**Describe the bug**
When EMS use their revive function it removes of armor of the player being revived.

**How to Reproduce the Behavior**
Steps to reproduce the behaviour:
Be an on duty EMS and use your Revive function on someone with body armor on.

**Expected Behaviour**
Expectedly the EMS or anyone using revive would not take the armor away.

**Additional context**
EMS taking away armor is an incentive to avoid them.
Reviving changes the food and level water or players lowering it if they were full.

**Comment by ChainedDev** [comment]
EMS taking your body armor is an incentive to avoid them. 

No, stop being a bitch and rp with ems.

We can however look into it

**Comment by Baja-Blast** [comment]
I am EMS trying to give more reason for people to stop by and actually get help rather than checking into the hospital. Thank you for looking into this

**Comment by Wally-W** [comment]
Also as an EMS I just wanted to add: This helps Police as well. Any time they go down and we help them up, it fully removes their armor and they need to return to the police station to resupply, or risk going back on duty without armor. 

This includes passing out from starvation/dehydration, getting hit by a car, getting knocked out from punches, falling down, and other situations where the armor shouldn't really be removed due to their injuries. I've seen many scenarios where police end up going down again mainly because their armor was removed before they had a chance to go get a fresh set.

An example I can think of is one time while a squad was trying to arrest a gang member, an officer was knocked out from a flashlight and we helped him up, removing his armor in the process. A few minutes later, other gang members tried saving their friend from being arrested, and they shot the officer we just helped up — since he had no armor left, he was easily downed.

If someone is involved in a shootout, then their armor has already taken damage or has been removed entirely from the bullets, so I'd say the penalty for it has already applied in those cases.

**Comment by ChainedDev** [comment]
> I am EMS trying to give more reason for people to stop by and actually get help rather than checking into the hospital. Thank you for looking into this

Yeah, I understand that it does have a problem but people shouldn't really not interact with EMS on purpose for something as little as Shield

**Comment by ChainedDev** [comment]
Both the hospital and being revived by EMS both take your armor, wasn't able to see only the hospital doing it when checking in, If they are dead and getting revived their body armor should be taken off when dying, also when being treated body armor would be off
