### ISSUE TITLE
Repair kits And wheels 

### ISSUE THREAD

**Issue by goldbee2g** [ChainedDev/CityLife#416]
**Is your feature request related to a problem?
Yes it is unrealistic for an advanced repair kit to repair say for example 4 broken tires. In my first suggestion you said that repair kits fix engine damage while advanced repair kits fix all damage to the car. But I guess you misunderstood the feature I was requesting.

**Describe the feature you'd like**
What I am asking for is that the regular repair kit remains the same, and the advanced repair kit will repair Repair do what it currently does but then it also re-pops the currently popped tires so if you end up with popped tires you can’t just use an advanced repair kit to fix it. You would have to go and get item “wheel” from tool store for say 150$, and spend 15 seconds or so replacing it for yourself. This same feature should apply to when the car is taken in and out of the garage.
**Additional context**
Since I don’t think you understood the feature I was requesting I can show you a video from another server of taking out a car that has popped tires (it basically takes the car out and then pops the tires again). Also if you used a repair kit on that server it just repairs all hull damage and engine damage (like the advanced repair kit in citylife). I’ll dm you a video sometime today

**Comment by AfricanGod47** [comment]
You seem to really want this feature in the city, but are you sure others would as well, I understand your point of it's not realistic but there is a crossing line between RP and the actual real world. There are going to be items that do more than what realistically is possible that's why it is still a game at the end of the day. I'm just saying that I don't believe this feature is necessary for our city but if a Dev agrees with you then, I'm happy regardless of the outcome.
