### ISSUE TITLE
PRISON ROLEPLAY UPDATES

### ISSUE THREAD

**Issue by xGRIMEYx** [ChainedDev/CityLife#530]
**Is your feature request related to a problem? Please describe.**
[Not really an issue, but more of an improvement on an area of roleplay that is lacking.]

**Describe the feature you'd like**
[I feel there should be a major addition or improvement to the prison life aspect of the city. There really isn't any roleplay aspect to being in prison unless someone else happens to be in prison with you and that is rarely the case. I feel like there are a couple of small ideas that could help push this in a more interesting direction: 1. Adding local prisoners into the prison to give it some life. The fact that it's empty is kind of a buzzkill. It would be great to have some activity in the prison by adding inmates in orange jumpsuits that have the personalities and aggro of the gangs such as Ballas and Vagos. That way fights can break out and stuff if you bump into or annoy one of them. 2. Another idea would be to put a secret tattoo location in one of the jail cells or in the jail yard. That way when in prison you can get "prison tats" with designs that are specific to the prison tattoo location only. This also brings another special aspect and lore to the crim life of the city when you see a prison tattoo on some, you know they've done some time.]

**Describe alternatives you've considered**
[No alternatives, JUST DO IT! lol]

**Additional context**
[]

**Comment by Sturdyinnit** [comment]
Love the prison tattoo

**Comment by TimmyTwoStep** [comment]
I agree with this, its part of the city that heavily lacks in RP, I mean when you compare it to the situation you where in prior to, being involved and then arrested by the cops, which offers a high volume of Roleppay behind it, then you're thrown in jail doing absolutely nothing.

When I had a criminal character, my group was asked by someone to get in to prison, and beat a gang down that wss locked inside. That would of pretty fire if we played it out, but unfortunately we didn't.

I think some sort of correction system would be nice to have, but I thinknwould be pretty hard to pull off consistently. Would involve having enough officers for SASP throwing people in jail for the Correction officers to monitor.

One thing I would love to see someone create some kind of gang that's is locked in prison for life and basically just start running the block. Prison RP lacking because yo don't have much to work with, the most you get is you have a warrant to raid properties
