### ISSUE TITLE
Dynasty 8 App showing you houses for sale and or rent

### ISSUE THREAD

**Issue by MikeBrowni3** [ChainedDev/CityLife#587]
**Is your feature request related to a problem? Same deal. There are very little Dynasty 8 Agents online. Very hard to see what is for sale and what is not.

**Describe the feature you'd like**

Overall like to see an App showing the homes the Dynasty 8 agents have setup for Rent and or Sale. Link their contact info to each house they are selling. 

**Describe alternatives you've considered**

Other options maybe have for Sale signs or For Rent signs up on the houses Dynasty 8 Agents have setup and allow you to click on the sign to see the price of the Rent, Lease or Sale Price. Also allow you to see the Agent linked to the house with his contact info. 

**Additional context**

Making it a little more real with contact info and for sale/rent/lease signs. Having to Tweet over and over to see if an Agent is in the City is rough and is not really up to 2021 Standards with the mobile phones.  Updating the phone and linking more to the mobile phone apps will forsure push City Life above the rest of the GTAV RP servers.

**Comment by honeybones** [comment]
So a few comments about this suggestion. Dynasty 8 actually doesn't set up houses for sale, almost every property is available for purchase and on the market in the city unless otherwise already owned. If you are looking for an agent to assist you with purchasing a property, we never suggest using Twitter. Dynasty agents are met by appointment, and we require clients to fill out the format in looking-for-agent in the Discord, and an agent reaches out to them. Dynasty 8 doesn't deal with anything but sales, and we do provide listings in the dynasty-listings channel to give you an idea of what we offer, but realistically the best bet is to speak one-on-one with your agent after making an appointment and they can use their experience to help you get what you want!

**Comment by Chainedster** [comment]
Check their discord channel
