### ISSUE TITLE
A blatant homophobia/transphobia issue causes me and many others not to want to rp

### ISSUE THREAD

**Issue by Elasticoochie** [ChainedDev/CityLife#627]
everytime me or someone else i know speaks we are hit with immediate slurs and attacks and even targeted to get robbed simply for existing

not all of us can get shadow play or have the capacity for recording software (shadow play , medal , etc.)

and without it , it feels shitty to play on this server. and while transphobia , racism , homophobia is against the rules i dont feel like police officers or anyone really enforces it in game. I've been to the police station or even picked up from an EMS where me as a trans woman have been remarked as "a man" and jokes like "it's ma'am" get thrown around (not by everyone but a select few). it genuinely feels terrible because i dont have the memory capabilties to record it. it would just help if maybe it was enforced by officers in game maybe not as an actual game breaking law but just a warn then maybe a ban. It would be very helpful to making me and my lgbt friends actually want to rp.

**Comment by MiGrane4Mayor** [comment]
There is no warn for that. It is an immediate ban. We are a staff that works at a limited capacity so we ALWAYS require the help of citizens and civilians. Unfortunately if we dont see it, theres absolutely nothing we can do. I AGREE 100000% it is NOT tolerated in any way shape or form if we do have it (the clip). But as a police man who takes RP very seriously, if someone broke rp to tell me hey ban that guy or arrest that guy for breaking a rule id push for a ban on both of you when I'm back in my office doing paperwork. Just because one person breaks RP, It doesnt justify another person breaking RP as well. The bottom line here is Roleplay Over Ruleplay. As staff i can say WE need that clip. Especially if we're not there. But as staff I can also say if we recieve evidence of that blatant rule break they would be banned ASAP. This is/ should be a safe for every race, sex, nationality, and preference. And you not having the memory to grab that clip will not supercede into a rule violation where cops are now having to deal with fail rp. I also have to add. Not every cop is a moderator, and as staff not every staff is a moderator. I hate that you were exposed to that because it goes against everything I belive in but my hands personally are tied. *There's zero tolerance for that rule break*. Hope this helps understand how we're structured here.
