### ISSUE TITLE
Vehicle and Property Taxes

### ISSUE THREAD

**Issue by MatthewHall-Basic** [ChainedDev/CityLife#628]
as much as people are going to hate this suggestion because its going to drain their hard earned coin, idc <3. I think there should be vehicle and property taxes. The reason being is we are getting to the point where every other car you see is a mclaren or a lambo, and no im not being a salty kid whos mad people have stuff i dont, i have owned a mclaren and lambo for months now. I think instilling a vehicle tax will add a little more realism and make people think twice before dumping 98% of their money into a 1+ million dollar car. This will also serve as a money drain that will keep the economy balanced and allow for a longer wipe period. We all saw what too many class 2s did to the city, I can only imagine what too much money is going to do. I believe this will also inspire people to find better sources of income to match their lifestyle and new tax bracket. Let me know what you guys think, im open to hearing the pros and cons, plz dont hate me its just a suggestion. <3

**Comment by MiGrane4Mayor** [comment]
Property tax is coming! Not sure about vehicle tax though. I see where your going with this though. It just seems super unrealistic? perhaps I can link that to like renewing your tags on a year basis which includes your vehicle tax? But the price doesnt vary based on make or model irl and its so cheap it wouldn't put a dent on our economy. Drug prices were fixed to help mitigate and now Property tax is comin to mitigate somewhat housing needs, if you have a business license there is a monthly tax as well. And police have been fining abandoned cars on the side of the road for illegal dumping, and illegally parking! I want more suggestions because I do feel the same way about the economy!
