### ISSUE TITLE
direct bank payments for businesses/houses

### ISSUE THREAD

**Issue by lemonjezus** [ChainedDev/CityLife#632]
**Is your feature request related to a problem? Please describe.**
cash payments is the way of the past time for the future!

**Describe the feature you'd like**
for any owner of a house or business i think it would be way easier and less tedious if we could simply choose the automated payment directly into the bank especially with businesses if theres employees or customers to be able to make them pay directly without any bank hassle and decide the amount of payment and frequency could be really nice

**Describe alternatives you've considered**
cash but im a man of the future i want the internet ag to be fully implemented on city life

**Additional context**
lets say you run a car renting business and you say its i dont know, 250 per hour. well now with the automated business you dont have to run after the customer yo u can just put it on auto and it charges them automatically until they stop their contracts with you it can go from 1 hour to 1 week or whatever you have as a business.

**Comment by MiGrane4Mayor** [comment]
Won't work for a car rental. The car reverts back the the owners insurance lot every tsunami so they charge up front for all 6 hrs. For everything else is pretty much back transfer already. To buy a house (bank)  to buy a car (bank) to get a mortgage (bank) to rent a car (bank). If you rent (bank) you could do bank transfer directly because the bank act number never changes. I think they allow the account being transferred to, to not even have to be in city. I think the auto payments your more focused on could be used to exploit and rob others on a "subscription " basis. just my 2 cents! I see what you going for but I don't think it's necessary.
