### ISSUE TITLE
Dead Bodys

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#698]
Make it so you can search dead bodies when there are 2 cops on makes class 2s being used less plus it's more realistic people and please add comments on what's wrong with these suggestions. not reactions with no reason why this wouldn't be good

**Comment by Forkedup** [comment]
Yes, while this may initially be a good idea on paper, it would not play out well in the city.

People would go straight to killing & then looting. They have all the more reason just to straight kill you rather then try to rob you and provide some roleplay.

This has been discussed, and dismissed due to the fact that we are a public server, and we know that not everyone will behave. It'll be more nuisance than anything. It will create many, many problems.
