### ISSUE TITLE
Wars

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#708]
In my opinion with gang wars, cops should wait until the wars over then go in to clear up the other side or go arrest some people this way is probably more realistic because I don't think cops would go into a war zone shooting at both sides when there putting their own lives In danger plus this makes both sides happy and it's a win-win the cops get their arrests and the 2 gangs or mafia gets to decipher which side won. I'm pretty sure most cops would disagree with this but there have been multiple times where cops have got involved in wars and there's never a clear winner in the end for example this clip https://medal.tv/clips/51401824/d1337LmacOXv the cops will just pop them heavy body armours and its pretty much impossible to down them even if the opponent is using a c2 and oxy the m4 can kill you in like 4 shots so i mean i feel like every war would have a clear winner

**Comment by zeako34** [comment]
So what are you saying is that cops shouldn't respond to shots fired? Or respond and only pick up bodies most of the time it happens they still shoot at us.
If you want to do gang wars go to sandy on the desert or something, if you shoot in the city I can tell that if there is any cops on duty they will respond there...
Also, body vests ain't that op It takes so much time that people can outrun us and shoot us when we are still picking them, and crime can just pop oxy that taxes a couple of seconds and still go.
Even in the given clip, you can see a guy popping oxy and going back to shooting
Another EDIT: Tropper on the clip took 1 heavy vest when the "gangsters" at the same time could pop 5 oxy which I belive gives you full armor and then they went to a close combat in which trooper didn't use any medical stuff but the "gangster" popped 2~3 oxy and between poping them still shoot

**Comment by TimmyTwoStep** [comment]
Cops not responding to a shoot out is kinda silly of them, though I do see where you are coming from saying we should fear for our lives, to an extent I can agree with this, only in cases where there really is no chance for you to do anything, like only officer on duty and 2 gangs are killing each other with 5 on each side, then it would make sense for use not to engage with a shoot but even then, I would still try an engage the scene safely as possible. I have been apart of the SASP since June of last year and have gotten a good idea of how to engage in these situations, but if there is a shoot out and we got multiple officers on scene, I'm running in looking to drop people. Just under half of the PD have M4s, and I would say at least 6-10 of those people are actually around all the time.  We also have the heavy body armor, which doesn't stop bleeding when compared to Oxy, you guys be poppin that shit like its goddamn candy going up ladders and on the back of BMW S1000s. Pak only used one vest while ripping my last one in the clip you shared. You could hear the commutation between him and I in the clip, that we know how to engage on the scenes.  

To conclude it all, if your gang is having a shoot out with another and the SASP is around, expect resistance, SASP on Top!

**Comment by TrooperJoe** [comment]
Be smart with how you set terms. If you are going to set a single location you better plan on cops showing up. Find the opps, hit a lick, and dip. When you stick around cops are going to show up. In the clip you can see the cop getting the high ground and taking them out without any officers going down. It’s not like he just drove straight into the middle of everything and and got lit up. And people that have access to tons of oxy and are complaining about body armor are really reaching... as someone that is on both sides  oxy is way better than our body armor.  Not to mention that the guys that we shot in that clip all had heavy body armor on them. It’s not about what you are using it’s about how you are using it.

**Comment by CREASE-C13** [comment]
I'm saying a cadet shouldn't be there firing a Glock and I'm just saying how wars need to be handled the right way a cop wouldn't run into a middle of the field shooting people like that gang members, yeah but cops would defend their own life a bit more it should be handled right such as swat coming in and handling it better such as sniping from a far and with oxy its getting nerfed soon and having body armor is way better you just have to get in cover and you can put it on way faster than oxy as well as that with the terms yeah there's some better locations but just would be better if there was a clear winner instead of cops that win 99 percent of the time

**Comment by TrooperJoe** [comment]
Not going to write another paragraph. All I will say is that cops are going to continue to respond to shots fired, especially when we can do it without any officers going down. Remember this is serious rp not realistic rp.
