### ISSUE TITLE
Nerf Cops

### ISSUE THREAD

**Issue by Carbineee** [ChainedDev/CityLife#710]
**What is the reason for this balance request?**

Every member of the police department has full armour no matter what rank it makes gun fights with PD literally impossible because it takes ages to kill them.

**What solution would you like?**

If you are not part of the state Emergency Response team you should only have a light bullet proof vest or armour, not a heavy duty vest.

**Additional context**

With the oxy nerf  that is coming, and with how long it takes a civilian to get 6-7 oxy and joints for full armour it seems very unbalanced and unfair, considering how easy it is for them to also get AR's

**Comment by Suedi4** [comment]
First of all, learn to shoot. Killing someone with full body armor isn’t more than 3-4 shots to the dome.

Then I want to ask you in what alternate universe it’s realistic to have an even balance between a police force and some skunked up hoodlums? This whole suggestion is pepega to me. Ain’t no way a cops body armor should be limited because criminals needs easier wins. You already got s1000 that everyone is rocking, you got an overflow of class 2 weaponry when not even half the pd is issued an M4. You got these crack heads that spam oxy, which to me is both failrp and not valuing life if we wanna reach for it, ever heard of an overdose? 

I just don’t understand why an unfair equipment comparison shouldn’t be a thing, considering the server is labeled as “serious” RP. This is not Chicago crack rp, not everyone and their moma got an rpg in the bathroom. Logically speaking, cops should have the advantage when it comes to equipment. 

Just a tip, use your brain and you might not get caught with whatever you are doing.
SASP ON TOP

**Comment by Carbineee** [comment]
I understand oxy spamming is fail RP, I never said it wasn't and this is being nerfed in the future so oxy is less powerful, in what universe is every member of PD wearing a kevlar level vest & helmet, I also see cops streaming with spare sets of armour in their inventory so the problem is the same, they can just pop another armour plate and be full armour again. The SERT / CERT / SWAT (Idk what its called here) should be able to use this higher level of armour, but your every day traffic officers shouldn't have full armour, its not about learning to shoot, I have to hit someone 4-6 times to drain their armour and kill them, a cop has to shoot me 2 times, I think its easier for them to hit 2 shots, than it is for us to hit 6 (This is just common sense)

I understand people have s1000's but this isn't everyone, you can't use this, the s1000 is 100k + people starting out wont have near enough money for this, but I guarantee every cop will have full armour.

**Comment by Suedi4** [comment]
So what you are saying is that new people should have an easier time to kill cops? Well that’s stupid, how often do you see some thugs kill 8 cops in a store robbery? It doesn’t happen man...

As for the armor, I try to rp it out whenever I put on a new vest, either go in my car to grab one or just open the trunk. Since it’s not realistic to have spare body vests in your pocket, but I try to compensate by limiting my self which I make sure to talk to other cops about too. But maybe some people rp that their plates are replaceable and they just toss out the shot one and slide in a fresh plate. It’s all up to the immersion, but as a whole there is no way a cop should be on a equal level with some criminals when it comes to equipment.

**Comment by Carbineee** [comment]
Okay, you're speaking of your experience, every encounter with police that results in a shootout, ends up having cops popping shields left right and centre as the shields weigh what, 1 gram? I never said they should be on equal playing fields, but either massively increasing the time it takes to put them on, increasing their weight so you can only carry 1 extra shield at a time, having a medium shield that gives half armour instead of full armour for anyone that isn't command or part of a response team, these are all balance changes. I'm not asking for cops to be on a level playing field by all means, but right now, their shields are way too overpowered.

**Comment by AnineAhmetovic** [comment]
only logical thing i can think of is to make it, that cops have to go into their trunk to put on a new set of body armor.

**Comment by JordanAdams12** [comment]
In my opinion, for cops to have full armor and a good weapon instils fear into criminals, and actually should prompt you to fear them. If you want cops to be nerfed it’s subject to your own want to kill them, you shouldn’t want to kill police, you want to evade them unless killing is absolutely necessary. You’re meant to fear police, don’t treat them like other criminals and see them as a potential shootout, because they’re equipped to put you down.
