### ISSUE TITLE
Robbing Stores

### ISSUE THREAD

**Issue by themorganheffer** [ChainedDev/CityLife#711]
**What is the reason for this balance request?' I feel like robbing the 24/7 is much more risk then reward and you really don't get anything out of it 

**What solution would you like?**
I think it should be a better payout instead of the 4-5k, Or make banks easier to hit, it would be really cool to see some more bank robbery rp as I don't think alot of people have ever hit a bank 

**Additional context**
I robbed 3 stores the other day with a crew and only got 4k out of it, Last store we got caught charge ends up being 26k, The reward is nowhere near the amount of risk for robbing a store currently

**Comment by Carbineee** [comment]
I agree, we hit a store yesterday with a hostage (Only just got out) and got 1k dirty money each, the reward is no where near the attention and possible charges / fines it draws.

**Comment by Esquibar** [comment]
1. Request an attorney via Attorney app. 2. Penal code currently lacks lesser charges like attempted robbery, accessory to robbery. 3. Cops frequently stack unnecessary charges like anti-mask, brandishing firearm 4. Cops also will charge suspects for robbery without evidence, tools, CCTV footage, dirty money 5. Fines can be reduced in some areas or robbery payout needs to be greater.

DOJ is more active than ever before. Much of these changes will play out in time, but devs can consider making the robbery more generous due to weight of the fines. Smo Main

**Comment by Dollar82** [comment]
Store robbing is to obtain other things,to do other things...The payout is just fine because you all only hit up north stores

**Comment by themorganheffer** [comment]
I only rob the stores in the city to make it a good rp scene for everyone
