### ISSUE TITLE
Even Cop Distribution Across Servers

### ISSUE THREAD

**Issue by baldmeister92** [ChainedDev/CityLife#722]
**What is the reason for this balance request?**
Ultimately, more often than not, all of the cops end up on server 1. Yesterday I think there were something like 8 or 11 concurrent police officers on server 1, and none that I noticed on server 2. In addition to this, queues for server 1 are consistently extremely long, numbering between 30-50 during peak playtime hours. For this reason, having a policy to divvy cops between both servers would solve these two problems. More cops on server 2 would allow the server 2 players to enjoy more roleplay experiences, especially relating to crime, while also lowering queue times for server 1. People would have an actual reason to join server 2. Right now, no one wants to join server 2 because you, majority of the time, cannot roleplay as a criminal on it. Basically, more people would get to play the characters they want more often.

**What solution would you like?**
A policy that, say, when more than X amount of cops are on server 1, send the extras to server 2 so that server 2 also has cops on it.

**Comment by YoungArtorious** [comment]
There's alot of reasons cops hardly fly into City 2. Most people in City 2 look at it as their opportunity to make money rather than actually RP, so they go into city 2 with this no intention to RP mindset and so when police go to interact with criminals, it results in people either immediately shooting at police or Combat Logging to avoid loosing their precious virtual items. Another thing with City 2 is that it has a larger influx of players who aren't fully accustomed to all of the City's rules, and as a cop when you fly in and see all these people constantly breaking rules its overwhelming because it's simply something that doesn't occur hardly at all in City 1. There are a couple of my fellow officers who make a conscious effort to try and fly into City 2 at least a couple times a week and they're some colossal balled mf's for doing so. I personally don't know how to combat this imbalance, I feel this will be something that will just naturally exist as long as we have a City 1 and 2; my best answer would be to try your absolute hardest to get into City 1 if what you want is good Crim-Cop RP interaction, and to not be a shit-lord when you see/interact with cops on City 2.
