### ISSUE TITLE
Mechs-pay

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#742]
Mechs have to rely on tips and fairly hardly anybody who comes into shops tip anything I think It should work when somebody gets their car upgraded you get a %5 percent commission.

**Comment by TimmyTwoStep** [comment]
Get people to like you more as a mechanic 🤷‍♂️
I was making bread as a mechanic when I was doing work, I think its mostly because of bank transfers being inconsistent or something like that now. Tipping was a lot easier then so that is definitely one factor. But for commissions, from what I've heard it used to be that way before. It would be cool if it were this way, but definitely a little strong on money making. Someone comes in and drops full upgrades in a car, thats at least going to be 8k in commission, do that through out the day you're walking away with deep pockets.

In my opinion, shops by themselves are able to do this, I don't own one but a good idea I have is run sorta a weekly challenge amongst the shop and its employees,  is see who can do the most work or something in the vest fashion. Total it up at the end of the week and pick a winner for a bonus check

**Comment by CREASE-C13** [comment]
got to be honest though it shouldn't revolve around people liking you though and yeah even a %1 would help cause honestly there's going to be most people who don't want to tip at all or just don't like you that much

**Comment by Dollar82** [comment]
Or just charge your mech fees.

**Comment by CptCut** [comment]
can we have the city with more locals? the streets are empty its un immersive especially when the streets of LA are always packed. Whens there's practically 0 cars on the road, any additional cars would be nice to see.

**Comment by CREASE-C13** [comment]
it would be nice but makes the server lag more because it would take more resources up
