### ISSUE TITLE
Less strict adherence to real world for more fun.

### ISSUE THREAD

**Issue by developincognito** [ChainedDev/CityLife#753]
This might be an unpopular opinion but I have three suggestions:
- You should be able to use your own car for crimes, without fear of having it taken away or comitting fail RP.
- You should be able to open a business with a criminal record.
- You should only lose your gun license if you use discharge your weapon unlawfully or use it during a crime (which might be redundant because that would be unlawful). I think it is crazy that if you attempt to rob a store you lose your license even if you just surrendered when the cops showed up.

At the end of the day we're trying to create interesting a fun RP scenarios within a video game that hopefully all parties: crims, cops, ems, and any others, can enjoy the experience regardless of "winning" or "losing".

There are enough penalties for someone who breaks the law that we shouldn't be limiting the fun they are allowed to have for a set about of time (criminal record expungement) or indefinitely (use of personal cars).

I am creating this ticket/issue in hopes to have a discussion around these topics with the goal of either convincing those in charge that these would be good changes or for those in charge to help me understand why it is a bad idea and thus no changes will be made.

I appreciate your time spent reading this.

**Comment by TimmyTwoStep** [comment]
Robbing a store with a personal vehicle shouldn't be a thing, people would be using some of the fastest cars for it, Jugulars for example are like 180k and your hitting a 2k lick at the most, no bodys going to do that, yes it might be more fun but its just a silly thing to do, if you're a criminal you would want to be moving around smart. 

I'm sure there are cases were can open a business with criminals charges, at least own one to an extent, Its not the best example but I was mechanic boss before with a criminal record.



And people losing their weapons license over a store robbery just makes sense, if you commit any violent crime with a registered firearm, you would get it revoked immediately, I person never revoked someone's license who surrendered at a store, and know how most of the officers are within the SASP. I can say this doesn't sound like something they would do, just seems like too much. 

I'm all for more things being fun I agree, I don't care if we win or lose on scenes as SASP, but people in store robberies barely make any effort in actual escape plans, they might have a route they will take, and we'll catch on to it if you use it multiple times. I've been apart of the SASP since 6/25/20 and I can say I may have only seen like 5 scenes max with people using some kind of clever escape plan. 

Its a rule to have you mention if you have any outside help, I think that would only make sense on bank robberies, I know most officer including myself are not going to report you not announcing outside help. And I never seen someone take advantage of the rules if there are 10+ officers you can use 2 extra people on scene. Criminals could definitely try stepping things up, because a lot of the time scenes would end in shoot outs because that's all they know what to do, drive around the city a little bit in a chase, crash or vehicle gets disabled, get out shooting. You can do a lot of things before Police open fire, no one really knows how to take advantage of it

**Comment by developincognito** [comment]
I committed my first and only crime on the server and got everything taken from me: my gun license, hunting equipment, gun, musket, and lockpicks. I touched a safe because I was curious and surrendered immediately. After surrendering, I chatted, complied, and plead guilty of attempted robbery...

The judge will not allow a business license to be given to anyone with a criminal record, no matter how small.

I agree crims need to be smarter.

I'll respond to your other comments later when I'm done with work.

**Comment by developincognito** [comment]
I'd be interested in chatting with you more too. I've never RP'd as a cop, so I'm curious as to what cops have fun doing that would make the RP fun. Then I can take that and use that in my crim RP.

**Comment by MiGrane4Mayor** [comment]
I hate to be that guy, but it's a serious rp city. It might just not be the one for you if you like more leniency. I can speak on my personal behalf, the reason I joined originally was due to the fact, the city walked more on the line of reality.

**Comment by developincognito** [comment]
> I hate to be that guy, but it's a serious rp city. It might just not be the one for you if you like more leniency.


Your comment is frustrating for multiple reasons, mainly because you basically are suggesting that if I "don't like it, then leave".

Many serious RP servers have a different philosophy than this one regarding the complaints I've made above. In your opinion, what benefits to the RP environment are gained through the restrictions in place?

> the city walked more on the line of reality

Some quick googling suggests that there aren't any state or federal laws preventing felons from starting a business.

However, I do see that it is most common for criminals to rent cars (which our city doesn't have) when committing crime.

Additionally, I see that felons lose the ability to own a firearm at least during their sentence and probationary period.
