### ISSUE TITLE
City

### ISSUE THREAD

**Issue by CREASE-C13** [ChainedDev/CityLife#762]
it seems like the city is not doing  too well recently and seems like people are going to other servers or just taking breaks I just want to know what happened they said the casino was going to be released and I never saw that everyone waited 6 months for whitelist and only 2 groups got whitelist 1 group that has a bunch of staff in and have pretty good rp ngl and then the other was just a bit surprising the group took a break from the city and most of there members kept getting banned and still managed to get it I mean I'm just saying how it is tbh if others got whitelisted there would have been so much more players playing because it gives them something to do like scan for parts business deals and other activities and the normal players that play citylife would try to strive to get into these groups so they can have more activities to do and the reason why that wouldn't work now is one of the groups is merely impossible to get into and the other you hardly see any of them plus theres no lux dealers anywhere round the server anymore and it seems like city has just been dry recently with nothing to do i just want to see the city be successfull and i hope theres more activites to do in the future honestly if you was going to whitelist Pasta with that you should of whitelistes Glo,Gsm,THS,Lost,Familes,MOB just the fact how long these people have been in city and shown a lot of loyalty to the server matters i mean we have seen bans from almost everyone round here but thats why the three strike rule was implemeted i feel all of these groups should have been given a chance and maybe another system should of been set up on who gets this and get these items managed in a way where they cant go into the wrong hands.

**Comment by TimmyTwoStep** [comment]
Lost MC and Pasta are the only two whitelisted, personally speaking, those two are the only ones that deserve it in my opinion.

**Comment by CREASE-C13** [comment]
Obviously it’s your opinion I think lost deserves it 100 percent but pasta you hardly see around anymore there’s only like 10 all together that have flew in the past 6 months and 2 of them have got banned recently I’m just saying that’s the reason that nearly everyone doesn’t fly in cities buggy as fuck recently more Danny’s then ever no casino and a let down whitelist that everyone waited 6 months for it to be 2 groups and if pasta should get whitelisted then some more should of got whitelisted I forgot to mention abm as well but yeah

**Comment by CREASE-C13** [comment]
it's the reason why gangs left in the past like TMN etc because of whitelist this time it is the majority i mean GLO doesn't care cause they just get their stuff off of pasta but most of ths what i have seen have been out of city life and going on another server that im not going to mention so i mean its whatever i just think it should be reevaluated

**Comment by Ashytoon** [comment]
Those two groups were the only whitelisted organizations because they’re the only ones who didn’t go to acting up while waiting on whitelist. Many gangs just let their actions go, and didn’t think anything of it. Speak for yourself / your own gang, don’t claim to know what’s going on with other gangs.

**Comment by Suedii** [comment]
I just can’t understand why you are claiming that neither pasta or lost are around. And it sounds more like you are lazy and don’t want to go through the proper channels in order for progress in your roleplaying. Why complain about not being able to join one of the 2 whitelisted groups when you can try to set up contact with them or whatever, it all comes down to how you rp. Pasta don’t wanna do deals with you? Maybe Rp2FindOut how you can set up a business deal with them? Lost don’t want to take you in their gang? Maybe not walk in to their clubhouse and ask to become a member. Please use your brain while trying to RP, and don’t be discouraged by setbacks as that is a great reason to develope your character/gangs agenda against certain people/groups. Last but not least, the reason to why other gangs and groups didn’t get whitelisted is because they are shitters. I like many of them but the last months before the update none of the gangs you mentioned could act accordingly, and all I saw from them was boredom and lack of creativity bc of tunnel vision at wanting to become whitelisted.

**Comment by PastaGodReggie** [comment]
For whatever reason you don't seem like the biggest fan of pasta, I could care less. Being whitelisted means you been recognized to give great RP, "so lets enhance that". If some one in the group is banned, Pasta disciplines their members. Unless its something major they're gone from the group. But to continue turning a blind eye to the fact all the gangs you listed, not inlcuding The Lost, have had multiple bans over the last 6 months is bias imo.  Also what's wrong with having 10 members? You only can use 5, stop this "build-me-an-army" mentality. Quality over quantity. Stop worrying about what goes on with pasta when you don't RP with them and worry about why some gangs haven't been whitelisted. Especially "Tickle Me Nuts", they been gone for months stop relishing on the past. Stop expressing on things you "think" is going on and get educated. If gangs want to leave the server because them sucking dick isn't getting them what they want, then bye. If those same gangs where buying their RP, instead of Rp2FindOut, not our fault. Its very unfortunate that some people don't know who came before Pasta Boys. #RPallOrganic

**Comment by LeeMast3r** [comment]
Seen THS around, and they have very bad image of theirself. Going as 7 or 10 people to fuck 2 guys up etc, seen that, even been there.

**Comment by randomcommenter12** [comment]
considering THS has never been banned for going over numbers this is not true. THS has been seen consistently shooting at people, but its because people shoot at them first for no reason. There has been a group of hackers making different characters and gangs just to target them for the past week and nothing seems to be getting handled. The city is just down bad in general.

**Comment by CREASE-C13** [comment]
That’s what I have been saying bruh cities dead nothing to do anymore that’s why everyone’s shooting waited 6 months for 2 gangs to get whitelisted overhyped the update like crazy said there was gonna be a casino everything has been more buggy then ever just terrible to be honest
