### ISSUE TITLE
Robbing-Meta

### ISSUE THREAD

**Issue by wmzombie** [ChainedDev/CityLife#797]
**What is the reason for this balance request?**
There has been a new rise of very low RP robbing at illegal and nonillegal locations. Not everyone is running body cam all the time to be able to report most of them

**What solution would you like?**
I think the best solution by far would be to make it so you can only rob people if there are 6 cops in the city. (Currently, it is 2) By doing this people that do this all the time (which is unconstitutional) will be incentivized to find a new line of work and only do it when the risk is higher

**Additional context**
I and many others will agree that this has become a very bad issue in the city and I have thought of many different ways of going about it including removing robbing altogether (considering this is not a whitelisted server), but by far this is definitely the way to go about it.

**Comment by Kiffy99** [comment]
To add to this ive been in the server for a bit now and ive always helped new/vulnerable players get on their feet a bit as a nice friendly into into a new city. But the complaint I hear a lot from these people is that they're robbed all the time poor quality low RP robbings. Ive been robbed numerous times and its quite the hassle to have to have to go around recording all your gameplay because of these thieves. Its putting an issue that's plagued numerous serves ive been a part of and to see it plague this server and put a bad taste in new and old players alike is sad. I too agree that the robbing should have a higher penalty and increase the circumstance that robberies can happen. Having to hound down admins or wait for un-responding EMS is ridiculous and after grinding for hours with nothing at a mine or fishing to get robbed before you can even get a gun license its absurd. Robbing is to easy to get into and way too easy to get away with, which encourages more robbing and the cycle continues. Its time we stand up against the people tainting this server.
