### ISSUE TITLE
fix housing

### ISSUE THREAD

**Issue by BenjiStoneHenji** [ChainedDev/CityLife#798]
going in and out of houses is a death sentence. not sure whats causing black screens or portals to not show up after entering but it needs to be fixed. and then after flying back in to get unstuck it shouldnt take hours to get a revive. hours of rp lost bc of bugs that cause me and others to sacrifice everything we have on us if we want to play and not wait ages.

possible fix - move houses to underground layers instead of floating up in the sky. if we reconnect we fall lower and pop up at the surface like when cars fall through the road and you jump out.

**Comment by wmzombie** [comment]
This fix is exactly what I was thinking as well. That is how robbing houses work. If you go under the world at least you will poof back onto the surface. I and many others have experienced this and it is really frustrating. Also having houses underneath makes it so your personal vehicle is less likely to despawn (Which is a serious issue itself)

**Comment by SANEofTheFix** [comment]
I bought a business with an interior and have this issue as well. I die multiple times a day just attempting to enter due to infinite loading screens and falling from the sky. Couple that with furniture disappearing all over the place and I’m wondering why we even bother spending money on apartments or interior businesses at all.
